### ISSUE TITLE
error `Could not find command "__local".`

### ISSUE THREAD

**Issue by alexanderadam** [asdf-vm/asdf-plugins#1088]
### Describe the Bug

I'm using `asdf` GitHub actions like this to [be able to skip some plugins](https://github.com/asdf-vm/actions/issues/566):

```yaml
    - name: Install asdf
      uses: asdf-vm/actions/setup@v3
    - name: Install asdf plugins
      uses: asdf-vm/actions/plugins-add@v3
    - name: Install asdf tools
      run: |
        asdf install ruby
        asdf install nodejs
        asdf install yarn
```

However, I'm getting the error message `Could not find command "__local"`:

```
[staging-deploy] ⭐ Run Main Build Docker image
[staging-deploy]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4.sh] user= workdir=
| ----------
| 
| NOTICE:
| 
| You have tried to upgrade to asdf 0.16.0 or newer. Versions 0.16.0 is a
| complete rewrite of asdf in Go. This text is being printed by the older
| Bash implementation. If you are seeing this you have not migrated to
| asdf 0.16.0. Please follow the instructions on the upgrade guide to
| migrate to the new version.
| 
| Aside from this notice, this older Bash implementation works as it did
| in asdf version 0.15.0 and older.
| 
| Migration guide: https://asdf-vm.com/guide/upgrading-to-v0-16
| asdf website: https://asdf-vm.com
| Source code: https://github.com/asdf-vm/asdf
| 
| 
| Could not find command "__local".
[staging-deploy]   ❌  Failure - Main Build Docker image
[staging-deploy] exitcode '1': failure
[staging-deploy] ⭐ Run Post Base setup
[staging-deploy]   ✅  Success - Post Base setup
[staging-deploy] ⭐ Run Complete job
[staging-deploy]   ✅  Success - Complete job
[staging-deploy] 🏁  Job failed
```

`.tool-versions` looks like this:

```
ruby 3.2.2
postgres 14.2
redis 7.0.15
nodejs 18.16.1
yarn 1.22.22
```

### Steps to Reproduce

1. use the above config
2. see the error

### Expected Behaviour

it should work

### Actual Behaviour

error `Could not find command "__local".`

### Environment

```shell
On my local machine probably not, right?
I can add that if you tell me how.
```
