### ISSUE TITLE
list-all GitHub releases on OSX fails

### ISSUE THREAD

**Issue by tomdavidson** [asdf-vm/asdf-plugins#31]
Hi, I have a plugin that fails list-all in OSX but not Linux and am hoping to get some pointers from OSX users.

- failed osx test: https://travis-ci.org/td7x/asdf-terragrunt/jobs/360733037
- pass linux test: https://gitlab.com/td7x/asdf/terragrunt/-/jobs/48771595

list-all:
```shell
#!/usr/bin/env bash

releases_path=https://api.github.com/repos/gruntwork-io/terragrunt/releases
cmd="curl -s $releases_path"

function sort_versions() {
  sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' | \
    LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | awk '{print $2}'
}

echo $(eval "$cmd" | grep -oE "tag_name\": \".{1,15}\"," | sed 's/tag_name\": \"v//;s/\",//' | sort_versions)
```

**Comment by vic** [comment]
hm, your script is working on my mac. :/

![screen shot 2018-04-03 at 1 44 32 am](https://user-images.githubusercontent.com/331/38233598-b46c23c4-36e0-11e8-9958-713482608e23.png)

**Comment by tomdavidson** [comment]
Thanks @vic 

Looks like I am missing the new lines in list-all on osx, but the travis job should pass.

Here's the trafis config:

```yaml
language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script: 
  - asdf plugin-add terragrunt ./
  - asdf list-all terragrunt
  - asdf plugin-test terragrunt ./ 'terragrunt --version'
os:
  - osx
```

Which is the same as this passing asdf plugin: https://travis-ci.org/td7x/asdf-adr-tools
